### PR TITLE
Add compatibility to OctoPrint 1.6

### PR DESCRIPTION
**Pull request by ElNinjaGaiden**

### CODE REVIEW

**Review by tfurci — APPROVED** [review]

**Comment by dimo414** [comment]
@gruvin can this change be merged?

**Comment by ElNinjaGaiden** [comment]
It can be merged in the sense the fix works. I know because I've installed the plugin pointing to my branch on my 3 printers and I'm using it from there until this gets merged (and it works).

Only the owner/somebody with write access can actually merge it.

**Comment by dimo414** [comment]
Yep, that's why I pinged the repo owner 😉

**Review by 7FM — COMMENTED** [review]
How about moving the default case with fallthrough right before these cases too:
```
default:
                console.log("plugin_Webcam Tab: Unsupported OctoPrint version " + OctoVersion)
case "1.5":
case "1.6":
```
(Side note: I am no javascript programmer so I am not sure if this is legal in javascript)
This would have the benefit of at least trying the latest solution, which likely works for newer versions too, instead of failing silently with no fallback solution.

**Comment by ElNinjaGaiden** [comment]
> How about moving the default case with fallthrough right before these cases too:
> 
> ```
> default:
>                 console.log("plugin_Webcam Tab: Unsupported OctoPrint version " + OctoVersion)
> case "1.5":
> case "1.6":
> ```
> 
> (Side note: I am no javascript programmer so I am not sure if this is legal in javascript)
> This would have the benefit of at least trying the latest solution, which likely works for newer versions too, instead of failing silently with no fallback solution.

I like it. I'm going to add it to my PR.
And yeah, if this doesn't get approved/merged by tomorrow, I'll be merging to master on my fork and then considering my fork as "official" I guess

**Comment by gruvin** [comment]
Sorry guys. I didn't receive any of this until today, for some messed up reason. I've gone ahead and merged the PR but I'll also check the (annoyingly required) copy/pasted portion of OctoPrint 1.6 code, in case there been any change.

**Comment by dimo414** [comment]
@gruvin can you cut a new release too?

**Comment by gruvin** [comment]
I did, Is it not showing up?

**Comment by dimo414** [comment]
Thanks! The update is now showing up on my OctoPrint instance, but when I click update it runs, restarts, and appears to still be at the prior release 😕  might be something wrong on my end but I'm not sure what. Even uninstalling and reinstalling gets me back to 0.2.0, despite the [plugin browser screen showing 0.2.1](https://user-images.githubusercontent.com/1885701/119180085-ae40bf80-ba24-11eb-9244-07f80ba60b03.png). Here's the [install output](https://pastebin.com/n7LVckvH) I see in OctoPrint, sorry the newlines got mangled but you can see it's installing 0.2.0.

**Comment by gruvin** [comment]
Should be offering 0.2.11 now, which will break out of that loop. An OP restart may be required also.

**Comment by dimo414** [comment]
I'm up and running! Thanks for your help :)

**Comment by gruvin** [comment]
Awesome. Sorry once again for the delays.

**Pull request merged**
