### PR TITLE
Update webcamtab.js

### PR DESCRIPTION
**Pull request by elfco**
Update for octoprint 1.7

### CODE REVIEW

**Comment by 7FM** [comment]
> > I would still like to see a more future proof patch as previously mentioned in: [#8 (review)](https://github.com/gruvin/OctoPrint-WebcamTab/pull/8#pullrequestreview-653538439)
> 
> I have change the patch to aply >1.5 code to the default statement, showing a posible error in log in new releases.

SGTM :)
Again, I have no Javascript knowledge but line 134: `if (OctoVersion > 1.7){` looks to me like a string to double comparison, which would not work with C-like languages. But does this work with JS?

**Comment by elfco** [comment]
Totally right, sorry for the mistake, i think now should work ok

**Comment by dimo414** [comment]
Thanks for contributing a future-proof fix! @gruvin can this be merged?

**Comment by gruvin** [comment]
Can someone let me know if the merge has worked for general distribution? I don't currently have a non-product OctoPrint to upgrade to 1.7 and work is keeping me stupid busy. Hopefully I'll get to it sooner than later but a little confirmation would be great in the meantime. Thanks.

**Comment by dimo414** [comment]
Confirmed installing via https://github.com/gruvin/OctoPrint-WebcamTab/archive/master.zip worked against 1.7.2.

And agreed this change doesn't prevent breakages in the future, but at least a breakage isn't hard-coded into place :)

**Comment by gruvin** [comment]
@dimo414 Thanks. Yeah, there was a time when it seemed every major release of OctoPrint (1.3 through 1.5 iirc?) broke the plugin and worse, screwed up the UI somewhat for, "reasons unknown to the user". Since that hasn't happened in 1.6 or 1.7, hopefully we'll be OK from here on out.

Note also that I only became the maintainer because the original fellow appears to have vanished. (We couldn't establish any contact.) It really depends on the season as to how active I am in 3D printing .... *so this PR was hugely appreciated*.

**Pull request merged**
